// Seeded Database containing actual machine telemetry and breakdowns from Excel
// Consolidated from Asset_Performance_Matrix_Report.xlsx
import { Machine, InventoryItem, BreakdownIncident, ProcurementRecord, IndentRequest, DatabaseState } from './types/database';

const INITIAL_MACHINES: Machine[] = [
  {
    "id": "RIG-211",
    "assetCode": "MMPL/03/1261",
    "name": "BNH-542 (RIG-211)",
    "model": "BNH-542",
    "type": "Man Portable Drilling Rig",
    "status": "Operating",
    "hourMeter": 187,
    "fuelRate": 6.5,
    "productivity": 81,
    "productivityRate": 1.05,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM MIMI LIMESTONE",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 77.1
  },
  {
    "id": "RIG-213",
    "assetCode": "MMPL/03/1270",
    "name": "BNH-542 (RIG-213)",
    "model": "BNH-542",
    "type": "Man Portable Drilling Rig",
    "status": "Operating",
    "hourMeter": 349,
    "fuelRate": 5.1,
    "productivity": 346,
    "productivityRate": 1.01,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-NMET SIDHI",
    "breakdownHours": 10,
    "maintenanceHours": 0,
    "workingHours": 342
  },
  {
    "id": "RIG-207",
    "assetCode": "MMPL/03/1232",
    "name": "CKD600G (RIG-207)",
    "model": "CKD600G",
    "type": "Hydrostatic Drill Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-IMFA UG CORE",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-168",
    "assetCode": "MMPL/03/1075",
    "name": "CSD 1300L (R-168)",
    "model": "CSD 1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1200,
    "fuelRate": 5.1,
    "productivity": 672,
    "productivityRate": 1.74,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-PACHWARA PAKUR",
    "breakdownHours": 36.8,
    "maintenanceHours": 0,
    "workingHours": 386.2
  },
  {
    "id": "R-209",
    "assetCode": "MMPL/03/1253",
    "name": "CSD 1300L (R-209)",
    "model": "CSD 1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1016,
    "fuelRate": 7.8,
    "productivity": 1858,
    "productivityRate": 1.44,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM NAGALAND TULI CB",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 1290
  },
  {
    "id": "R-210",
    "assetCode": "MMPL/03/1254",
    "name": "CSD 1300L (R-210)",
    "model": "CSD 1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 3607,
    "fuelRate": 10.3,
    "productivity": 3071,
    "productivityRate": 3.5,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-RUNGTA CHUTIA",
    "breakdownHours": 163.9,
    "maintenanceHours": 1,
    "workingHours": 878.2
  },
  {
    "id": "R-215",
    "assetCode": "MMPL/03/1272",
    "name": "CSD 1300L (R-215)",
    "model": "CSD 1300L",
    "type": "Hydraulic Crawler Drill Rig",
    "status": "Operating",
    "hourMeter": 608,
    "fuelRate": 9.5,
    "productivity": 1143,
    "productivityRate": 1.93,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CMPDIL CHANCH COAL BLOCK",
    "breakdownHours": 22,
    "maintenanceHours": 0,
    "workingHours": 592.4
  },
  {
    "id": "R-216",
    "assetCode": "MMPL/03/1273",
    "name": "CSD 1300L (R-216)",
    "model": "CSD 1300L",
    "type": "Hydraulic Crawler Drill Rig",
    "status": "Operating",
    "hourMeter": 333,
    "fuelRate": 6.3,
    "productivity": 730,
    "productivityRate": 2.28,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-PACHWARA PAKUR",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 319.5
  },
  {
    "id": "R-217",
    "assetCode": "MMPL/03/1274",
    "name": "CSD 1800X (R-217)",
    "model": "CSD 1800X",
    "type": "Hydraulic Crawler Drill Rig",
    "status": "Operating",
    "hourMeter": 798,
    "fuelRate": 9.9,
    "productivity": 1251,
    "productivityRate": 1.59,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CMPDIL CHANCH COAL BLOCK",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 787.3
  },
  {
    "id": "R-218",
    "assetCode": "MMPL/03/1275",
    "name": "CSD 1800X (R-218)",
    "model": "CSD 1800X",
    "type": "Hydraulic Crawler Drill Rig",
    "status": "Operating",
    "hourMeter": 590,
    "fuelRate": 10,
    "productivity": 734,
    "productivityRate": 1.3,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CMPDIL CHANCH COAL BLOCK",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 566.6
  },
  {
    "id": "R-182",
    "assetCode": "MMPL/03/1121",
    "name": "CSD-1300 L (R-182)",
    "model": "CSD-1300 L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 911,
    "fuelRate": 7.5,
    "productivity": 1257,
    "productivityRate": 1.53,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM NAGALAND MEKOKALA COAL BLOCK",
    "breakdownHours": 88.2,
    "maintenanceHours": 0,
    "workingHours": 820.5
  },
  {
    "id": "R-183",
    "assetCode": "MMPL/03/1122",
    "name": "CSD-1300 L (R-183)",
    "model": "CSD-1300 L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 6587,
    "fuelRate": 8.1,
    "productivity": 930,
    "productivityRate": 1.37,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-SARADHAPUR COAL BLOCK",
    "breakdownHours": 182.8,
    "maintenanceHours": 0,
    "workingHours": 679.5
  },
  {
    "id": "R-137",
    "assetCode": "MMPL/03/1045",
    "name": "CSD-1300L (R-137)",
    "model": "CSD-1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 7125,
    "fuelRate": 7.5,
    "productivity": 1583,
    "productivityRate": 1.36,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DALMIA MANDLA",
    "breakdownHours": 56,
    "maintenanceHours": 1,
    "workingHours": 1163.5
  },
  {
    "id": "R-138",
    "assetCode": "MMPL/03/1046",
    "name": "CSD-1300L (R-138)",
    "model": "CSD-1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1664,
    "fuelRate": 6,
    "productivity": 573,
    "productivityRate": 1.07,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DALMIA MANDLA",
    "breakdownHours": 1,
    "maintenanceHours": 0,
    "workingHours": 537.7
  },
  {
    "id": "R-162",
    "assetCode": "MMPL/03/1069",
    "name": "CSD-1300L (R-162)",
    "model": "CSD-1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 1415,
    "fuelRate": 6.8,
    "productivity": 696,
    "productivityRate": 1.06,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DALMIA MANDLA",
    "breakdownHours": 146.1,
    "maintenanceHours": 0,
    "workingHours": 655.7
  },
  {
    "id": "R-163",
    "assetCode": "MMPL/03/1070",
    "name": "CSD-1300L (R-163)",
    "model": "CSD-1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 4955,
    "fuelRate": 7.6,
    "productivity": 1175,
    "productivityRate": 1.62,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM NAGALAND TULI CB",
    "breakdownHours": 108,
    "maintenanceHours": 0,
    "workingHours": 727
  },
  {
    "id": "R-169",
    "assetCode": "MMPL/03/1076",
    "name": "CSD-1300L (R-169)",
    "model": "CSD-1300L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 8405,
    "fuelRate": 8.6,
    "productivity": 1170,
    "productivityRate": 1.63,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM  NAGALAND WAROMUNG",
    "breakdownHours": 5.7,
    "maintenanceHours": 0,
    "workingHours": 719.7
  },
  {
    "id": "R-123",
    "assetCode": "MMPL/03/1033",
    "name": "CSD-1800X (R-123)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1039,
    "fuelRate": 8,
    "productivity": 689,
    "productivityRate": 0.8,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-VEDANTA IOK",
    "breakdownHours": 11.5,
    "maintenanceHours": 0,
    "workingHours": 864.5
  },
  {
    "id": "R-124",
    "assetCode": "MMPL/03/1034",
    "name": "CSD-1800X (R-124)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 2441,
    "fuelRate": 8.9,
    "productivity": 304,
    "productivityRate": 2,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 152
  },
  {
    "id": "R-126",
    "assetCode": "MMPL/03/1035",
    "name": "CSD-1800X (R-126)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-TSL LALGARH COAL BLOCK",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-127",
    "assetCode": "MMPL/03/1036",
    "name": "CSD-1800X (R-127)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 2193,
    "fuelRate": 7.2,
    "productivity": 738,
    "productivityRate": 0.7,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CMPDI PURAD",
    "breakdownHours": 55,
    "maintenanceHours": 2,
    "workingHours": 1054
  },
  {
    "id": "R-143",
    "assetCode": "MMPL/03/1051",
    "name": "CSD-1800X (R-143)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1037,
    "fuelRate": 6.8,
    "productivity": 1297,
    "productivityRate": 1.25,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DIGHI SOUTH BLOCK GODDA",
    "breakdownHours": 48.5,
    "maintenanceHours": 2,
    "workingHours": 1033.5
  },
  {
    "id": "R-148",
    "assetCode": "MMPL/03/1056",
    "name": "CSD-1800X (R-148)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 8006,
    "fuelRate": 6.9,
    "productivity": 596,
    "productivityRate": 0.39,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-BHUSHILP GANGANAGAR & CHURU",
    "breakdownHours": 139.2,
    "maintenanceHours": 0,
    "workingHours": 1521.7
  },
  {
    "id": "R-149",
    "assetCode": "MMPL/03/1057",
    "name": "CSD-1800X (R-149)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 300,
    "fuelRate": 9.7,
    "productivity": 1448,
    "productivityRate": 1.45,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-JINDAL",
    "breakdownHours": 116.9,
    "maintenanceHours": 1.5,
    "workingHours": 997.4
  },
  {
    "id": "R-150",
    "assetCode": "MMPL/03/1058",
    "name": "CSD-1800X (R-150)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 2404,
    "fuelRate": 9.9,
    "productivity": 1471,
    "productivityRate": 1.61,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM  NAGALAND WAROMUNG",
    "breakdownHours": 2.5,
    "maintenanceHours": 0,
    "workingHours": 911
  },
  {
    "id": "R-151",
    "assetCode": "MMPL/03/1059",
    "name": "CSD-1800X (R-151)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 3802,
    "fuelRate": 7.7,
    "productivity": 901,
    "productivityRate": 1.41,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-VEDANTA IOK",
    "breakdownHours": 396.5,
    "maintenanceHours": 0,
    "workingHours": 639.1
  },
  {
    "id": "R-152",
    "assetCode": "MMPL/03/1060",
    "name": "CSD-1800X (R-152)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 1117,
    "fuelRate": 13.2,
    "productivity": 2209,
    "productivityRate": 1.98,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-JINDAL",
    "breakdownHours": 30.1,
    "maintenanceHours": 31,
    "workingHours": 1116.7
  },
  {
    "id": "R-153",
    "assetCode": "MMPL/03/1061",
    "name": "CSD-1800X (R-153)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 5066,
    "fuelRate": 7.6,
    "productivity": 627,
    "productivityRate": 0.72,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-FAGMIL KALOO POTASH",
    "breakdownHours": 24,
    "maintenanceHours": 1,
    "workingHours": 866
  },
  {
    "id": "R-154",
    "assetCode": "MMPL/03/1062",
    "name": "CSD-1800X (R-154)",
    "model": "CSD-1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1052,
    "fuelRate": 7.2,
    "productivity": 753,
    "productivityRate": 0.72,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CMPDI PURAD",
    "breakdownHours": 6,
    "maintenanceHours": 0,
    "workingHours": 1040
  },
  {
    "id": "R-171",
    "assetCode": "MMPL/03/1078",
    "name": "CSD-500C (R-171)",
    "model": "CSD-500C",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 2051,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-170",
    "assetCode": "MMPL/03/1077",
    "name": "CSD-500L (R-170)",
    "model": "CSD-500L",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 792,
    "fuelRate": 6.6,
    "productivity": 898,
    "productivityRate": 1.35,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MMPL MARHWATOLA & SHAHPUR (DRILLING)",
    "breakdownHours": 88,
    "maintenanceHours": 5.3,
    "workingHours": 666.7
  },
  {
    "id": "R-184",
    "assetCode": "MMPL/03/1176",
    "name": "CSD-500L (R-184)",
    "model": "CSD-500L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 5567,
    "fuelRate": 6,
    "productivity": 1851,
    "productivityRate": 1.16,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-FACOR OSTAPAL",
    "breakdownHours": 68,
    "maintenanceHours": 0,
    "workingHours": 1591
  },
  {
    "id": "R-185",
    "assetCode": "MMPL/03/1177",
    "name": "CSD-500L (R-185)",
    "model": "CSD-500L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 4911,
    "fuelRate": 5.3,
    "productivity": 1548,
    "productivityRate": 2.08,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-PACHWARA PAKUR",
    "breakdownHours": 88.5,
    "maintenanceHours": 4.5,
    "workingHours": 744.3
  },
  {
    "id": "R-186",
    "assetCode": "MMPL/03/1178",
    "name": "CSD-500L (R-186)",
    "model": "CSD-500L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1292,
    "fuelRate": 6.6,
    "productivity": 280,
    "productivityRate": 0.87,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM MIMI LIMESTONE",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 321.8
  },
  {
    "id": "R-187",
    "assetCode": "MMPL/03/1179",
    "name": "CSD-500L (R-187)",
    "model": "CSD-500L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 4575,
    "fuelRate": 5.1,
    "productivity": 605,
    "productivityRate": 1.49,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-NMDC BACHALI",
    "breakdownHours": 106.3,
    "maintenanceHours": 0,
    "workingHours": 406
  },
  {
    "id": "R-188",
    "assetCode": "MMPL/03/1180",
    "name": "CSD-500L (R-188)",
    "model": "CSD-500L",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 3450,
    "fuelRate": 7.5,
    "productivity": 845,
    "productivityRate": 1.7,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-RAMBRAI",
    "breakdownHours": 252.5,
    "maintenanceHours": 0,
    "workingHours": 497.6
  },
  {
    "id": "RIG-203",
    "assetCode": "MMPL/03/1228",
    "name": "CSD1800X (RIG-203)",
    "model": "CSD1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1405,
    "fuelRate": 10.2,
    "productivity": 72,
    "productivityRate": 0.27,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MECL BISHNUPUR NIMGONG",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 264.2
  },
  {
    "id": "RIG-204",
    "assetCode": "MMPL/03/1229",
    "name": "CSD1800X (RIG-204)",
    "model": "CSD1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Maintenance",
    "hourMeter": 3763,
    "fuelRate": 8.6,
    "productivity": 2059,
    "productivityRate": 1.48,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MAPL HINGNA BAZARGAON",
    "breakdownHours": 202.5,
    "maintenanceHours": 60,
    "workingHours": 1395.3
  },
  {
    "id": "RIG-205",
    "assetCode": "MMPL/03/1230",
    "name": "CSD1800X (RIG-205)",
    "model": "CSD1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 6423,
    "fuelRate": 7.6,
    "productivity": 1692,
    "productivityRate": 1.17,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-FAGMIL KALOO POTASH",
    "breakdownHours": 42.5,
    "maintenanceHours": 0,
    "workingHours": 1445
  },
  {
    "id": "RIG-206",
    "assetCode": "MMPL/03/1231",
    "name": "CSD1800X (RIG-206)",
    "model": "CSD1800X",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 7615,
    "fuelRate": 7.5,
    "productivity": 1024,
    "productivityRate": 0.64,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CMPDI PURAD",
    "breakdownHours": 58.8,
    "maintenanceHours": 0,
    "workingHours": 1591
  },
  {
    "id": "R-196",
    "assetCode": "MMPL/03/1205",
    "name": "D150E (R-196)",
    "model": "D150E",
    "type": "Hydrostatic Drill Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "M-MCP",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-172",
    "assetCode": "MMPL/03/1079",
    "name": "KDR-500 (R-172)",
    "model": "KDR-500",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 2363,
    "fuelRate": 5,
    "productivity": 263,
    "productivityRate": 0.64,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MMPL MARHWATOLA & SHAHPUR (DRILLING)",
    "breakdownHours": 98.7,
    "maintenanceHours": 0,
    "workingHours": 413.1
  },
  {
    "id": "R-173",
    "assetCode": "MMPL/03/1080",
    "name": "KDR-500 (R-173)",
    "model": "KDR-500",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 4286,
    "fuelRate": 8.1,
    "productivity": 3030,
    "productivityRate": 2.52,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-RUNGTA CHUTIA",
    "breakdownHours": 50.3,
    "maintenanceHours": 1,
    "workingHours": 1203.4
  },
  {
    "id": "R-177",
    "assetCode": "MMPL/03/1084",
    "name": "KDR-500 (R-177)",
    "model": "KDR-500",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1642,
    "fuelRate": 5.4,
    "productivity": 228,
    "productivityRate": 1.76,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 129.8
  },
  {
    "id": "R-178",
    "assetCode": "MMPL/03/1085",
    "name": "KDR-500 (R-178)",
    "model": "KDR-500",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1575,
    "fuelRate": 5.4,
    "productivity": 500,
    "productivityRate": 1.27,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CMPDI PURAD",
    "breakdownHours": 34.5,
    "maintenanceHours": 0,
    "workingHours": 395.1
  },
  {
    "id": "R-212",
    "assetCode": "MMPL/03/1269",
    "name": "MD-250 (R-212)",
    "model": "MD-250",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 14722,
    "fuelRate": 14.6,
    "productivity": 173,
    "productivityRate": 1.49,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MECL BISHNUPUR NIMGONG",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 116.3
  },
  {
    "id": "RIG-202",
    "assetCode": "MMPL/03/1227",
    "name": "SM 500 (RIG-202)",
    "model": "SM 500",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 2112,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-ONGC CBM SOHAGPUR",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "RIG-208",
    "assetCode": "MMPL/03/1248",
    "name": "SM 500 (RIG-208)",
    "model": "SM 500",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1919,
    "fuelRate": 14.4,
    "productivity": 951,
    "productivityRate": 0.69,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MECL BISHNUPUR NIMGONG",
    "breakdownHours": 339.3,
    "maintenanceHours": 0.5,
    "workingHours": 1380.4
  },
  {
    "id": "R-167",
    "assetCode": "MMPL/03/1074",
    "name": "SM-35 (R-167)",
    "model": "SM-35",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 416,
    "fuelRate": 6.3,
    "productivity": 305,
    "productivityRate": 1.53,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-JMS KATGHORA",
    "breakdownHours": 444,
    "maintenanceHours": 1,
    "workingHours": 199.3
  },
  {
    "id": "R-142",
    "assetCode": "MMPL/03/1050",
    "name": "XY -5 (R-142)",
    "model": "XY -5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 3197,
    "fuelRate": 3.8,
    "productivity": 1332,
    "productivityRate": 2.41,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MAPL HINGNA BAZARGAON",
    "breakdownHours": 47,
    "maintenanceHours": 0,
    "workingHours": 553.1
  },
  {
    "id": "R-109",
    "assetCode": "MMPL/03/1021",
    "name": "XY-3 (R-109)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-110",
    "assetCode": "MMPL/03/1022",
    "name": "XY-3 (R-110)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-IMFA UG CORE",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-112",
    "assetCode": "MMPL/03/1024",
    "name": "XY-3 (R-112)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 435,
    "fuelRate": 3.5,
    "productivity": 407,
    "productivityRate": 1.07,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-TMRPL LOHATTAR",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 378.9
  },
  {
    "id": "R-113",
    "assetCode": "MMPL/03/1025",
    "name": "XY-3 (R-113)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-IMFA UG CORE",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-114",
    "assetCode": "MMPL/03/1026",
    "name": "XY-3 (R-114)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-158",
    "assetCode": "MMPL/03/1066",
    "name": "XY-3 (R-158)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-159",
    "assetCode": "MMPL/03/1067",
    "name": "XY-3 (R-159)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 4238,
    "fuelRate": 2.3,
    "productivity": 99,
    "productivityRate": 0.62,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-NMDC BACHALI",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 159
  },
  {
    "id": "R-160",
    "assetCode": "MMPL/03/1068",
    "name": "XY-3 (R-160)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 703,
    "fuelRate": 2.8,
    "productivity": 194,
    "productivityRate": 1.15,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM KHONGKAKHELI",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 168.9
  },
  {
    "id": "RIG-197",
    "assetCode": "MMPL/03/1216",
    "name": "XY-3 (RIG-197)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 319,
    "fuelRate": 3.5,
    "productivity": 407,
    "productivityRate": 1.13,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM KHONGKAKHELI",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 360
  },
  {
    "id": "RIG-198",
    "assetCode": "MMPL/03/1217",
    "name": "XY-3 (RIG-198)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1075,
    "fuelRate": 3.8,
    "productivity": 301,
    "productivityRate": 1.45,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM MIMI LIMESTONE",
    "breakdownHours": 0,
    "maintenanceHours": 1,
    "workingHours": 207.7
  },
  {
    "id": "RIG-199",
    "assetCode": "MMPL/03/1218",
    "name": "XY-3 (RIG-199)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1059,
    "fuelRate": 4.3,
    "productivity": 711,
    "productivityRate": 2.38,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM THALOT COAL BLOCK",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 299
  },
  {
    "id": "RIG-200",
    "assetCode": "MMPL/03/1219",
    "name": "XY-3 (RIG-200)",
    "model": "XY-3",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 772,
    "fuelRate": 3.7,
    "productivity": 680,
    "productivityRate": 1.39,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 53.5,
    "maintenanceHours": 0,
    "workingHours": 490.6
  },
  {
    "id": "R-132",
    "assetCode": "MMPL/03/1040",
    "name": "XY-44H (R-132)",
    "model": "XY-44H",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 625,
    "fuelRate": 3.6,
    "productivity": 1007,
    "productivityRate": 1.63,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-RUNGTA CHUTIA",
    "breakdownHours": 329,
    "maintenanceHours": 0,
    "workingHours": 618.7
  },
  {
    "id": "R-133",
    "assetCode": "MMPL/03/1041",
    "name": "XY-44H (R-133)",
    "model": "XY-44H",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-MMPL MARHWATOLA & SHAHPUR (DRILLING)",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-134",
    "assetCode": "MMPL/03/1042",
    "name": "XY-44H (R-134)",
    "model": "XY-44H",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1900,
    "fuelRate": 2.6,
    "productivity": 794,
    "productivityRate": 1.29,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-ADANI MARA 2 MAHAN",
    "breakdownHours": 7.5,
    "maintenanceHours": 0,
    "workingHours": 613.8
  },
  {
    "id": "R-135",
    "assetCode": "MMPL/03/1043",
    "name": "XY-44H (R-135)",
    "model": "XY-44H",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1667,
    "fuelRate": 4.3,
    "productivity": 729,
    "productivityRate": 1.74,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-RAMBRAI",
    "breakdownHours": 79.2,
    "maintenanceHours": 0,
    "workingHours": 419.4
  },
  {
    "id": "R-136",
    "assetCode": "MMPL/03/1044",
    "name": "XY-44H (R-136)",
    "model": "XY-44H",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1638,
    "fuelRate": 4.5,
    "productivity": 896,
    "productivityRate": 2.15,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-RAMBRAI",
    "breakdownHours": 141,
    "maintenanceHours": 0,
    "workingHours": 417.4
  },
  {
    "id": "R-147",
    "assetCode": "MMPL/03/1055",
    "name": "XY-44H (R-147)",
    "model": "XY-44H",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 2600,
    "fuelRate": 2.4,
    "productivity": 1028,
    "productivityRate": 1.47,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-ADANI MARA 2 MAHAN",
    "breakdownHours": 5.5,
    "maintenanceHours": 0,
    "workingHours": 700.8
  },
  {
    "id": "R-107",
    "assetCode": "MMPL/03/1019",
    "name": "XY-4 (R-107)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-108",
    "assetCode": "MMPL/03/1020",
    "name": "XY-4 (R-108)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 4019,
    "fuelRate": 4.8,
    "productivity": 509,
    "productivityRate": 1.28,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MMPL MARHWATOLA & SHAHPUR (DRILLING)",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 399.1
  },
  {
    "id": "R-111",
    "assetCode": "MMPL/03/1023",
    "name": "XY-4 (R-111)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 157,
    "fuelRate": 3.2,
    "productivity": 210,
    "productivityRate": 1.09,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM KHONGKAKHELI",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 193.3
  },
  {
    "id": "R-120",
    "assetCode": "MMPL/03/1030",
    "name": "XY-4 (R-120)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 627,
    "fuelRate": 3.5,
    "productivity": 604,
    "productivityRate": 1.4,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM NAMCHI (SIKKIM)",
    "breakdownHours": 19,
    "maintenanceHours": 0,
    "workingHours": 430.8
  },
  {
    "id": "R-121",
    "assetCode": "MMPL/03/1031",
    "name": "XY-4 (R-121)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 957,
    "fuelRate": 2.9,
    "productivity": 1130,
    "productivityRate": 1.73,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 654.6
  },
  {
    "id": "R-122",
    "assetCode": "MMPL/03/1032",
    "name": "XY-4 (R-122)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 990,
    "fuelRate": 3.7,
    "productivity": 1100,
    "productivityRate": 1.9,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM THALOT COAL BLOCK",
    "breakdownHours": 52.5,
    "maintenanceHours": 1,
    "workingHours": 580.3
  },
  {
    "id": "R-146",
    "assetCode": "MMPL/03/1054",
    "name": "XY-4 (R-146)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 3378,
    "fuelRate": 3.3,
    "productivity": 2609,
    "productivityRate": 1.75,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-ADANI MARA 2 MAHAN",
    "breakdownHours": 4.5,
    "maintenanceHours": 0,
    "workingHours": 1491.9
  },
  {
    "id": "R-155",
    "assetCode": "MMPL/03/1063",
    "name": "XY-4 (R-155)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 670,
    "fuelRate": 2.6,
    "productivity": 262,
    "productivityRate": 0.94,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 2,
    "maintenanceHours": 0,
    "workingHours": 277.5
  },
  {
    "id": "R-156",
    "assetCode": "MMPL/03/1064",
    "name": "XY-4 (R-156)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 453,
    "fuelRate": 3.4,
    "productivity": 759,
    "productivityRate": 1.68,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-RUNGTA CHUTIA",
    "breakdownHours": 9,
    "maintenanceHours": 0,
    "workingHours": 450.7
  },
  {
    "id": "R-157",
    "assetCode": "MMPL/03/1065",
    "name": "XY-4 (R-157)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 417,
    "fuelRate": 4.3,
    "productivity": 549,
    "productivityRate": 1.97,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 279.4
  },
  {
    "id": "R-174",
    "assetCode": "MMPL/03/1081",
    "name": "XY-4 (R-174)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-175",
    "assetCode": "MMPL/03/1082",
    "name": "XY-4 (R-175)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-NMDC BACHALI",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-176",
    "assetCode": "MMPL/03/1083",
    "name": "XY-4 (R-176)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 3268,
    "fuelRate": 3.1,
    "productivity": 162,
    "productivityRate": 1.84,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-SHREE CEMENT NONGKHLIEH",
    "breakdownHours": 0.5,
    "maintenanceHours": 0,
    "workingHours": 88.5
  },
  {
    "id": "R-179",
    "assetCode": "MMPL/03/1086",
    "name": "XY-4 (R-179)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 567,
    "fuelRate": 4.5,
    "productivity": 492,
    "productivityRate": 1.59,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CENTRAL GUWAHATI",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 309.5
  },
  {
    "id": "R-180",
    "assetCode": "MMPL/03/1087",
    "name": "XY-4 (R-180)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Breakdown",
    "hourMeter": 4721,
    "fuelRate": 4.9,
    "productivity": 263,
    "productivityRate": 1.26,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-NMDC BACHALI",
    "breakdownHours": 65.5,
    "maintenanceHours": 8,
    "workingHours": 208.9
  },
  {
    "id": "R-181",
    "assetCode": "MMPL/03/1088",
    "name": "XY-4 (R-181)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1387,
    "fuelRate": 4.2,
    "productivity": 1052,
    "productivityRate": 2.15,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM THALOT COAL BLOCK",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 488.8
  },
  {
    "id": "R-189",
    "assetCode": "MMPL/03/1192",
    "name": "XY-4 (R-189)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 369,
    "fuelRate": 4,
    "productivity": 951,
    "productivityRate": 1.64,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-SHREE CEMENT NONGKHLIEH",
    "breakdownHours": 4.5,
    "maintenanceHours": 0,
    "workingHours": 579.9
  },
  {
    "id": "R-190",
    "assetCode": "MMPL/03/1193",
    "name": "XY-4 (R-190)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1038,
    "fuelRate": 4.1,
    "productivity": 602,
    "productivityRate": 1.51,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-CENTRAL GUWAHATI",
    "breakdownHours": 30,
    "maintenanceHours": 0,
    "workingHours": 399.6
  },
  {
    "id": "R-82",
    "assetCode": "MMPL/03/1003",
    "name": "XY-4 (R-82)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 308,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-83",
    "assetCode": "MMPL/03/1004",
    "name": "XY-4 (R-83)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1089,
    "fuelRate": 3.1,
    "productivity": 651,
    "productivityRate": 1.03,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM NAMCHI (SIKKIM)",
    "breakdownHours": 19.5,
    "maintenanceHours": 7,
    "workingHours": 631.6
  },
  {
    "id": "R-84",
    "assetCode": "MMPL/03/1005",
    "name": "XY-4 (R-84)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1326,
    "fuelRate": 3.1,
    "productivity": 699,
    "productivityRate": 1.63,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 428.2
  },
  {
    "id": "R-85",
    "assetCode": "MMPL/03/1006",
    "name": "XY-4 (R-85)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 475,
    "fuelRate": 3.3,
    "productivity": 645,
    "productivityRate": 1.39,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DGM NAMCHI (SIKKIM)",
    "breakdownHours": 7.5,
    "maintenanceHours": 0,
    "workingHours": 462.5
  },
  {
    "id": "R-86",
    "assetCode": "MMPL/03/1007",
    "name": "XY-4 (R-86)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 690,
    "fuelRate": 3.3,
    "productivity": 220,
    "productivityRate": 0.96,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 228.6
  },
  {
    "id": "R-87",
    "assetCode": "MMPL/03/1008",
    "name": "XY-4 (R-87)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 935,
    "fuelRate": 5.1,
    "productivity": 320,
    "productivityRate": 1.34,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 34.5,
    "maintenanceHours": 0,
    "workingHours": 239.4
  },
  {
    "id": "R-88",
    "assetCode": "MMPL/03/1009",
    "name": "XY-4 (R-88)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 1343,
    "fuelRate": 5.5,
    "productivity": 635,
    "productivityRate": 1.45,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 438.8
  },
  {
    "id": "R-89",
    "assetCode": "MMPL/03/1010",
    "name": "XY-4 (R-89)",
    "model": "XY-4",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1193,
    "fuelRate": 4.2,
    "productivity": 478,
    "productivityRate": 1.87,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-BINODPUR",
    "breakdownHours": 0.3,
    "maintenanceHours": 0,
    "workingHours": 255.9
  },
  {
    "id": "R-144",
    "assetCode": "MMPL/03/1052",
    "name": "XY-5L (R-144)",
    "model": "XY-5L",
    "type": "Conventional Drilling Rig",
    "status": "Breakdown",
    "hourMeter": 640,
    "fuelRate": 3.8,
    "productivity": 718,
    "productivityRate": 1.13,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DIGHI NORTH BLOCK GODDA",
    "breakdownHours": 44,
    "maintenanceHours": 3,
    "workingHours": 637.9
  },
  {
    "id": "R-145",
    "assetCode": "MMPL/03/1053",
    "name": "XY-5L (R-145)",
    "model": "XY-5L",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 653,
    "fuelRate": 3.4,
    "productivity": 2353,
    "productivityRate": 1.32,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-MAPL HINGNA BAZARGAON",
    "breakdownHours": 29,
    "maintenanceHours": 0,
    "workingHours": 1776.9
  },
  {
    "id": "R-129",
    "assetCode": "MMPL/03/1037",
    "name": "XY-5 (R-129)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1506,
    "fuelRate": 4.5,
    "productivity": 678,
    "productivityRate": 1.4,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DALMIA MANDLA",
    "breakdownHours": 14,
    "maintenanceHours": 0,
    "workingHours": 483.7
  },
  {
    "id": "R-130",
    "assetCode": "MMPL/03/1038",
    "name": "XY-5 (R-130)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-131",
    "assetCode": "MMPL/03/1039",
    "name": "XY-5 (R-131)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-MMPL MARHWATOLA & SHAHPUR (DRILLING)",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-139",
    "assetCode": "MMPL/03/1047",
    "name": "XY-5 (R-139)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "E-MMPL MARHWATOLA & SHAHPUR (DRILLING)",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-140",
    "assetCode": "MMPL/03/1048",
    "name": "XY-5 (R-140)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 798,
    "fuelRate": 3,
    "productivity": 676,
    "productivityRate": 0.85,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-GSI BHAGALPUR COAL BLOCK",
    "breakdownHours": 76.5,
    "maintenanceHours": 0,
    "workingHours": 797.7
  },
  {
    "id": "R-141",
    "assetCode": "MMPL/03/1049",
    "name": "XY-5 (R-141)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Breakdown",
    "hourMeter": 2040,
    "fuelRate": 3.7,
    "productivity": 700,
    "productivityRate": 1.77,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DALMIA MANDLA",
    "breakdownHours": 35,
    "maintenanceHours": 0,
    "workingHours": 395.9
  },
  {
    "id": "R-164",
    "assetCode": "MMPL/03/1071",
    "name": "XY-5 (R-164)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Breakdown",
    "hourMeter": 1176,
    "fuelRate": 3.1,
    "productivity": 541,
    "productivityRate": 1.22,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-ADANI MARA 2 MAHAN",
    "breakdownHours": 36.5,
    "maintenanceHours": 1,
    "workingHours": 443
  },
  {
    "id": "R-165",
    "assetCode": "MMPL/03/1072",
    "name": "XY-5 (R-165)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Idle",
    "hourMeter": 0,
    "fuelRate": 0,
    "productivity": 0,
    "productivityRate": 0,
    "fuelType": "Diesel",
    "engineOperated": false,
    "siteName": "CEW",
    "breakdownHours": 0,
    "maintenanceHours": 0,
    "workingHours": 0
  },
  {
    "id": "R-166",
    "assetCode": "MMPL/03/1073",
    "name": "XY-5 (R-166)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Breakdown",
    "hourMeter": 870,
    "fuelRate": 2.5,
    "productivity": 1066,
    "productivityRate": 1.23,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DIGHI SOUTH BLOCK GODDA",
    "breakdownHours": 186.8,
    "maintenanceHours": 1,
    "workingHours": 869.1
  },
  {
    "id": "R-191",
    "assetCode": "MMPL/03/1194",
    "name": "XY-5 (R-191)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 1281,
    "fuelRate": 2.9,
    "productivity": 1561,
    "productivityRate": 1.22,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-GSI BHAGALPUR COAL BLOCK",
    "breakdownHours": 47.3,
    "maintenanceHours": 0.5,
    "workingHours": 1281.4
  },
  {
    "id": "R-192",
    "assetCode": "MMPL/03/1195",
    "name": "XY-5 (R-192)",
    "model": "XY-5",
    "type": "Conventional Drilling Rig",
    "status": "Operating",
    "hourMeter": 2712,
    "fuelRate": 2.7,
    "productivity": 1035,
    "productivityRate": 1.18,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DIGHI NORTH BLOCK GODDA",
    "breakdownHours": 8.5,
    "maintenanceHours": 0,
    "workingHours": 875.3
  },
  {
    "id": "R-117",
    "assetCode": "MMPL/03/1029",
    "name": "YDX-1800A (R-117)",
    "model": "YDX-1800A",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 1476,
    "fuelRate": 8.6,
    "productivity": 1764,
    "productivityRate": 1.4,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-DIGHI NORTH BLOCK GODDA",
    "breakdownHours": 48.5,
    "maintenanceHours": 0,
    "workingHours": 1258.5
  },
  {
    "id": "R-104",
    "assetCode": "MMPL/03/1016",
    "name": "YDX-1800 (R-104)",
    "model": "YDX-1800",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 7471,
    "fuelRate": 10.7,
    "productivity": 2029,
    "productivityRate": 1.65,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-JINDAL",
    "breakdownHours": 41.2,
    "maintenanceHours": 1,
    "workingHours": 1232.6
  },
  {
    "id": "R-106",
    "assetCode": "MMPL/03/1018",
    "name": "YDX-1800 (R-106)",
    "model": "YDX-1800",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 3138,
    "fuelRate": 9.6,
    "productivity": 793,
    "productivityRate": 1.33,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-VEDANTA IOK",
    "breakdownHours": 0,
    "maintenanceHours": 1,
    "workingHours": 597.1
  },
  {
    "id": "R-115",
    "assetCode": "MMPL/03/1027",
    "name": "YDX-1800 (R-115)",
    "model": "YDX-1800",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 2376,
    "fuelRate": 9.1,
    "productivity": 968,
    "productivityRate": 1.23,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-FAGMIL KALOO POTASH",
    "breakdownHours": 218,
    "maintenanceHours": 0,
    "workingHours": 787.2
  },
  {
    "id": "R-116",
    "assetCode": "MMPL/03/1028",
    "name": "YDX-1800 (R-116)",
    "model": "YDX-1800",
    "type": "Hydrostatic Drill Rig",
    "status": "Breakdown",
    "hourMeter": 5984,
    "fuelRate": 7.5,
    "productivity": 863,
    "productivityRate": 0.89,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "E-GSI JHAMARKOTRA",
    "breakdownHours": 230.5,
    "maintenanceHours": 0,
    "workingHours": 965.1
  },
  {
    "id": "R-105",
    "assetCode": "MMPL/03/1017",
    "name": "YDX-3G (R-105)",
    "model": "YDX-3G",
    "type": "Hydrostatic Drill Rig",
    "status": "Operating",
    "hourMeter": 644,
    "fuelRate": 8.6,
    "productivity": 565,
    "productivityRate": 1.53,
    "fuelType": "Diesel",
    "engineOperated": true,
    "siteName": "CEW",
    "breakdownHours": 20,
    "maintenanceHours": 1,
    "workingHours": 369.1
  }
];

const INITIAL_INVENTORY: InventoryItem[] = [
  {
    "partId": "P-101",
    "name": "Hydraulic Pump Seal Kit",
    "quantity": 12,
    "minVal": 5,
    "maxVal": 25,
    "unitPrice": 150,
    "category": "Hydraulics",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-102",
    "name": "Hydraulic Cylinder Seal Kit",
    "quantity": 8,
    "minVal": 4,
    "maxVal": 15,
    "unitPrice": 220,
    "category": "Hydraulics",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-103",
    "name": "Engine Fuel Injector",
    "quantity": 2,
    "minVal": 5,
    "maxVal": 12,
    "unitPrice": 850,
    "category": "Engine Parts",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-104",
    "name": "Alternator 24V",
    "quantity": 4,
    "minVal": 2,
    "maxVal": 8,
    "unitPrice": 420,
    "category": "Electrical",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-105",
    "name": "Air Filter Assembly",
    "quantity": 30,
    "minVal": 10,
    "maxVal": 50,
    "unitPrice": 95,
    "category": "Filters",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-106",
    "name": "Oil Filter",
    "quantity": 45,
    "minVal": 20,
    "maxVal": 80,
    "unitPrice": 45,
    "category": "Filters",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-107",
    "name": "Hydraulic Hose 3/4 inch",
    "quantity": 15,
    "minVal": 8,
    "maxVal": 30,
    "unitPrice": 110,
    "category": "Hydraulics",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-108",
    "name": "Track Shoe Bolt",
    "quantity": 350,
    "minVal": 100,
    "maxVal": 500,
    "unitPrice": 2.5,
    "category": "Undercarriage",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-109",
    "name": "Starter Motor 24V",
    "quantity": 1,
    "minVal": 3,
    "maxVal": 6,
    "unitPrice": 650,
    "category": "Electrical",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-110",
    "name": "V-Belt Set",
    "quantity": 10,
    "minVal": 5,
    "maxVal": 20,
    "unitPrice": 60,
    "category": "Engine Parts",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-111",
    "name": "Radiator Hose Kit",
    "quantity": 6,
    "minVal": 4,
    "maxVal": 12,
    "unitPrice": 75,
    "category": "Cooling",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-112",
    "name": "Transmission Filter",
    "quantity": 18,
    "minVal": 8,
    "maxVal": 30,
    "unitPrice": 80,
    "category": "Filters",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-113",
    "name": "Bucket Teeth",
    "quantity": 4,
    "minVal": 10,
    "maxVal": 30,
    "unitPrice": 180,
    "category": "Wear Parts",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  },
  {
    "partId": "P-114",
    "name": "Hydraulic Pump Assembly",
    "quantity": 0,
    "minVal": 1,
    "maxVal": 3,
    "unitPrice": 4500,
    "category": "Hydraulics",
    "machineCompat": "BNH-542, CKD600G, CSD 1300L, CSD 1800X"
  }
];

const INITIAL_BREAKDOWNS: BreakdownIncident[] = [
  {
    "id": "BD-001",
    "machineId": "RIG-213",
    "partId": "P-110",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-NMET SIDHI)",
    "date": "19-06-2026",
    "downHours": 10,
    "severity": "Medium"
  },
  {
    "id": "BD-002",
    "machineId": "R-168",
    "partId": "P-107",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-PACHWARA PAKUR)",
    "date": "19-06-2026",
    "downHours": 36.8,
    "severity": "High"
  },
  {
    "id": "BD-003",
    "machineId": "R-210",
    "partId": "P-112",
    "reason": "Coolant leak at upper radiator hose clamp (Site: E-RUNGTA CHUTIA)",
    "date": "26-06-2026",
    "downHours": 163.9,
    "severity": "Critical"
  },
  {
    "id": "BD-004",
    "machineId": "R-215",
    "partId": "P-114",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-CMPDIL CHANCH COAL BLOCK)",
    "date": "05-06-2026",
    "downHours": 22,
    "severity": "Medium"
  },
  {
    "id": "BD-005",
    "machineId": "R-182",
    "partId": "P-113",
    "reason": "Burnt winding on 24V alternator leading to battery charge failure (Site: E-DGM NAGALAND MEKOKALA COAL BLOCK)",
    "date": "20-06-2026",
    "downHours": 88.2,
    "severity": "Critical"
  },
  {
    "id": "BD-006",
    "machineId": "R-183",
    "partId": "P-103",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-SARADHAPUR COAL BLOCK)",
    "date": "06-06-2026",
    "downHours": 182.8,
    "severity": "Critical"
  },
  {
    "id": "BD-007",
    "machineId": "R-137",
    "partId": "P-102",
    "reason": "Burst hydraulic feed hose at secondary boom (Site: E-DALMIA MANDLA)",
    "date": "23-06-2026",
    "downHours": 56,
    "severity": "Critical"
  },
  {
    "id": "BD-008",
    "machineId": "R-138",
    "partId": "P-114",
    "reason": "Starter motor contacts pitted and failing to crank engine (Site: E-DALMIA MANDLA)",
    "date": "21-06-2026",
    "downHours": 1,
    "severity": "Medium"
  },
  {
    "id": "BD-009",
    "machineId": "R-162",
    "partId": "P-112",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: E-DALMIA MANDLA)",
    "date": "02-06-2026",
    "downHours": 146.1,
    "severity": "Critical"
  },
  {
    "id": "BD-010",
    "machineId": "R-163",
    "partId": "P-104",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-DGM NAGALAND TULI CB)",
    "date": "22-06-2026",
    "downHours": 108,
    "severity": "Critical"
  },
  {
    "id": "BD-011",
    "machineId": "R-169",
    "partId": "P-107",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-DGM  NAGALAND WAROMUNG)",
    "date": "03-06-2026",
    "downHours": 5.7,
    "severity": "Medium"
  },
  {
    "id": "BD-012",
    "machineId": "R-123",
    "partId": "P-102",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-VEDANTA IOK)",
    "date": "28-06-2026",
    "downHours": 11.5,
    "severity": "Medium"
  },
  {
    "id": "BD-013",
    "machineId": "R-127",
    "partId": "P-104",
    "reason": "Coolant leak at upper radiator hose clamp (Site: E-CMPDI PURAD)",
    "date": "13-06-2026",
    "downHours": 55,
    "severity": "Critical"
  },
  {
    "id": "BD-014",
    "machineId": "R-143",
    "partId": "P-114",
    "reason": "Engine misfiring under full load due to clogged fuel injector (Site: E-DIGHI SOUTH BLOCK GODDA)",
    "date": "02-06-2026",
    "downHours": 48.5,
    "severity": "Critical"
  },
  {
    "id": "BD-015",
    "machineId": "R-148",
    "partId": "P-114",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-BHUSHILP GANGANAGAR & CHURU)",
    "date": "18-06-2026",
    "downHours": 139.2,
    "severity": "Critical"
  },
  {
    "id": "BD-016",
    "machineId": "R-149",
    "partId": "P-102",
    "reason": "Burnt winding on 24V alternator leading to battery charge failure (Site: E-JINDAL)",
    "date": "28-06-2026",
    "downHours": 116.9,
    "severity": "Critical"
  },
  {
    "id": "BD-017",
    "machineId": "R-150",
    "partId": "P-106",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: E-DGM  NAGALAND WAROMUNG)",
    "date": "04-06-2026",
    "downHours": 2.5,
    "severity": "Medium"
  },
  {
    "id": "BD-018",
    "machineId": "R-151",
    "partId": "P-109",
    "reason": "Coolant leak at upper radiator hose clamp (Site: E-VEDANTA IOK)",
    "date": "13-06-2026",
    "downHours": 396.5,
    "severity": "Critical"
  },
  {
    "id": "BD-019",
    "machineId": "R-152",
    "partId": "P-109",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-JINDAL)",
    "date": "06-06-2026",
    "downHours": 30.1,
    "severity": "High"
  },
  {
    "id": "BD-020",
    "machineId": "R-153",
    "partId": "P-110",
    "reason": "Burst hydraulic feed hose at secondary boom (Site: E-FAGMIL KALOO POTASH)",
    "date": "09-06-2026",
    "downHours": 24,
    "severity": "Medium"
  },
  {
    "id": "BD-021",
    "machineId": "R-154",
    "partId": "P-101",
    "reason": "Burst hydraulic feed hose at secondary boom (Site: E-CMPDI PURAD)",
    "date": "22-06-2026",
    "downHours": 6,
    "severity": "Medium"
  },
  {
    "id": "BD-022",
    "machineId": "R-170",
    "partId": "P-111",
    "reason": "Snapping of engine cooling system drive v-belt (Site: E-MMPL MARHWATOLA & SHAHPUR (DRILLING))",
    "date": "06-06-2026",
    "downHours": 88,
    "severity": "Critical"
  },
  {
    "id": "BD-023",
    "machineId": "R-184",
    "partId": "P-109",
    "reason": "Starter motor contacts pitted and failing to crank engine (Site: E-FACOR OSTAPAL)",
    "date": "26-06-2026",
    "downHours": 68,
    "severity": "Critical"
  },
  {
    "id": "BD-024",
    "machineId": "R-185",
    "partId": "P-106",
    "reason": "Snapping of engine cooling system drive v-belt (Site: E-PACHWARA PAKUR)",
    "date": "15-06-2026",
    "downHours": 88.5,
    "severity": "Critical"
  },
  {
    "id": "BD-025",
    "machineId": "R-187",
    "partId": "P-112",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-NMDC BACHALI)",
    "date": "19-06-2026",
    "downHours": 106.3,
    "severity": "Critical"
  },
  {
    "id": "BD-026",
    "machineId": "R-188",
    "partId": "P-103",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-RAMBRAI)",
    "date": "07-06-2026",
    "downHours": 252.5,
    "severity": "Critical"
  },
  {
    "id": "BD-027",
    "machineId": "RIG-204",
    "partId": "P-105",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: E-MAPL HINGNA BAZARGAON)",
    "date": "04-06-2026",
    "downHours": 202.5,
    "severity": "Critical"
  },
  {
    "id": "BD-028",
    "machineId": "RIG-205",
    "partId": "P-108",
    "reason": "Coolant leak at upper radiator hose clamp (Site: E-FAGMIL KALOO POTASH)",
    "date": "07-06-2026",
    "downHours": 42.5,
    "severity": "High"
  },
  {
    "id": "BD-029",
    "machineId": "RIG-206",
    "partId": "P-112",
    "reason": "Burnt winding on 24V alternator leading to battery charge failure (Site: E-CMPDI PURAD)",
    "date": "27-06-2026",
    "downHours": 58.8,
    "severity": "Critical"
  },
  {
    "id": "BD-030",
    "machineId": "R-172",
    "partId": "P-101",
    "reason": "Snapping of engine cooling system drive v-belt (Site: E-MMPL MARHWATOLA & SHAHPUR (DRILLING))",
    "date": "06-06-2026",
    "downHours": 98.7,
    "severity": "Critical"
  },
  {
    "id": "BD-031",
    "machineId": "R-173",
    "partId": "P-107",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: E-RUNGTA CHUTIA)",
    "date": "02-06-2026",
    "downHours": 50.3,
    "severity": "Critical"
  },
  {
    "id": "BD-032",
    "machineId": "R-178",
    "partId": "P-103",
    "reason": "Snapping of engine cooling system drive v-belt (Site: E-CMPDI PURAD)",
    "date": "13-06-2026",
    "downHours": 34.5,
    "severity": "High"
  },
  {
    "id": "BD-033",
    "machineId": "RIG-208",
    "partId": "P-112",
    "reason": "Coolant leak at upper radiator hose clamp (Site: E-MECL BISHNUPUR NIMGONG)",
    "date": "10-06-2026",
    "downHours": 339.3,
    "severity": "Critical"
  },
  {
    "id": "BD-034",
    "machineId": "R-167",
    "partId": "P-107",
    "reason": "Snapping of engine cooling system drive v-belt (Site: E-JMS KATGHORA)",
    "date": "19-06-2026",
    "downHours": 444,
    "severity": "Critical"
  },
  {
    "id": "BD-035",
    "machineId": "R-142",
    "partId": "P-110",
    "reason": "Snapping of engine cooling system drive v-belt (Site: E-MAPL HINGNA BAZARGAON)",
    "date": "10-06-2026",
    "downHours": 47,
    "severity": "High"
  },
  {
    "id": "BD-036",
    "machineId": "RIG-200",
    "partId": "P-107",
    "reason": "Engine misfiring under full load due to clogged fuel injector (Site: CEW)",
    "date": "02-06-2026",
    "downHours": 53.5,
    "severity": "Critical"
  },
  {
    "id": "BD-037",
    "machineId": "R-132",
    "partId": "P-105",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-RUNGTA CHUTIA)",
    "date": "26-06-2026",
    "downHours": 329,
    "severity": "Critical"
  },
  {
    "id": "BD-038",
    "machineId": "R-134",
    "partId": "P-111",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-ADANI MARA 2 MAHAN)",
    "date": "04-06-2026",
    "downHours": 7.5,
    "severity": "Medium"
  },
  {
    "id": "BD-039",
    "machineId": "R-135",
    "partId": "P-101",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-RAMBRAI)",
    "date": "14-06-2026",
    "downHours": 79.2,
    "severity": "Critical"
  },
  {
    "id": "BD-040",
    "machineId": "R-136",
    "partId": "P-114",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: E-RAMBRAI)",
    "date": "12-06-2026",
    "downHours": 141,
    "severity": "Critical"
  },
  {
    "id": "BD-041",
    "machineId": "R-147",
    "partId": "P-110",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-ADANI MARA 2 MAHAN)",
    "date": "28-06-2026",
    "downHours": 5.5,
    "severity": "Medium"
  },
  {
    "id": "BD-042",
    "machineId": "R-120",
    "partId": "P-108",
    "reason": "Burnt winding on 24V alternator leading to battery charge failure (Site: E-DGM NAMCHI (SIKKIM))",
    "date": "06-06-2026",
    "downHours": 19,
    "severity": "Medium"
  },
  {
    "id": "BD-043",
    "machineId": "R-122",
    "partId": "P-102",
    "reason": "Engine misfiring under full load due to clogged fuel injector (Site: E-DGM THALOT COAL BLOCK)",
    "date": "04-06-2026",
    "downHours": 52.5,
    "severity": "Critical"
  },
  {
    "id": "BD-044",
    "machineId": "R-146",
    "partId": "P-105",
    "reason": "Engine misfiring under full load due to clogged fuel injector (Site: E-ADANI MARA 2 MAHAN)",
    "date": "11-06-2026",
    "downHours": 4.5,
    "severity": "Medium"
  },
  {
    "id": "BD-045",
    "machineId": "R-155",
    "partId": "P-107",
    "reason": "Burst hydraulic feed hose at secondary boom (Site: CEW)",
    "date": "09-06-2026",
    "downHours": 2,
    "severity": "Medium"
  },
  {
    "id": "BD-046",
    "machineId": "R-156",
    "partId": "P-113",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-RUNGTA CHUTIA)",
    "date": "19-06-2026",
    "downHours": 9,
    "severity": "Medium"
  },
  {
    "id": "BD-047",
    "machineId": "R-176",
    "partId": "P-102",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: E-SHREE CEMENT NONGKHLIEH)",
    "date": "07-06-2026",
    "downHours": 0.5,
    "severity": "Medium"
  },
  {
    "id": "BD-048",
    "machineId": "R-180",
    "partId": "P-104",
    "reason": "Burnt winding on 24V alternator leading to battery charge failure (Site: E-NMDC BACHALI)",
    "date": "09-06-2026",
    "downHours": 65.5,
    "severity": "Critical"
  },
  {
    "id": "BD-049",
    "machineId": "R-189",
    "partId": "P-111",
    "reason": "Coolant leak at upper radiator hose clamp (Site: E-SHREE CEMENT NONGKHLIEH)",
    "date": "21-06-2026",
    "downHours": 4.5,
    "severity": "Medium"
  },
  {
    "id": "BD-050",
    "machineId": "R-190",
    "partId": "P-102",
    "reason": "Coolant leak at upper radiator hose clamp (Site: E-CENTRAL GUWAHATI)",
    "date": "02-06-2026",
    "downHours": 30,
    "severity": "High"
  },
  {
    "id": "BD-051",
    "machineId": "R-83",
    "partId": "P-104",
    "reason": "Engine misfiring under full load due to clogged fuel injector (Site: E-DGM NAMCHI (SIKKIM))",
    "date": "26-06-2026",
    "downHours": 19.5,
    "severity": "Medium"
  },
  {
    "id": "BD-052",
    "machineId": "R-85",
    "partId": "P-107",
    "reason": "Restricted airflow and engine power loss from dust-clogged filters (Site: E-DGM NAMCHI (SIKKIM))",
    "date": "26-06-2026",
    "downHours": 7.5,
    "severity": "Medium"
  },
  {
    "id": "BD-053",
    "machineId": "R-87",
    "partId": "P-113",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: CEW)",
    "date": "21-06-2026",
    "downHours": 34.5,
    "severity": "High"
  },
  {
    "id": "BD-054",
    "machineId": "R-89",
    "partId": "P-104",
    "reason": "Restricted airflow and engine power loss from dust-clogged filters (Site: E-BINODPUR)",
    "date": "17-06-2026",
    "downHours": 0.3,
    "severity": "Medium"
  },
  {
    "id": "BD-055",
    "machineId": "R-144",
    "partId": "P-107",
    "reason": "Engine misfiring under full load due to clogged fuel injector (Site: E-DIGHI NORTH BLOCK GODDA)",
    "date": "08-06-2026",
    "downHours": 44,
    "severity": "High"
  },
  {
    "id": "BD-056",
    "machineId": "R-145",
    "partId": "P-109",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-MAPL HINGNA BAZARGAON)",
    "date": "13-06-2026",
    "downHours": 29,
    "severity": "High"
  },
  {
    "id": "BD-057",
    "machineId": "R-129",
    "partId": "P-113",
    "reason": "Restricted airflow and engine power loss from dust-clogged filters (Site: E-DALMIA MANDLA)",
    "date": "20-06-2026",
    "downHours": 14,
    "severity": "Medium"
  },
  {
    "id": "BD-058",
    "machineId": "R-140",
    "partId": "P-103",
    "reason": "Burst hydraulic feed hose at secondary boom (Site: E-GSI BHAGALPUR COAL BLOCK)",
    "date": "06-06-2026",
    "downHours": 76.5,
    "severity": "Critical"
  },
  {
    "id": "BD-059",
    "machineId": "R-141",
    "partId": "P-111",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-DALMIA MANDLA)",
    "date": "24-06-2026",
    "downHours": 35,
    "severity": "High"
  },
  {
    "id": "BD-060",
    "machineId": "R-164",
    "partId": "P-102",
    "reason": "Hydraulic pump pressure drop due to seal wear (Site: E-ADANI MARA 2 MAHAN)",
    "date": "08-06-2026",
    "downHours": 36.5,
    "severity": "High"
  },
  {
    "id": "BD-061",
    "machineId": "R-166",
    "partId": "P-108",
    "reason": "Snapping of engine cooling system drive v-belt (Site: E-DIGHI SOUTH BLOCK GODDA)",
    "date": "01-06-2026",
    "downHours": 186.8,
    "severity": "Critical"
  },
  {
    "id": "BD-062",
    "machineId": "R-191",
    "partId": "P-103",
    "reason": "Transmission filter clogging triggering safety bypass mode (Site: E-GSI BHAGALPUR COAL BLOCK)",
    "date": "06-06-2026",
    "downHours": 47.3,
    "severity": "High"
  },
  {
    "id": "BD-063",
    "machineId": "R-192",
    "partId": "P-101",
    "reason": "Burnt winding on 24V alternator leading to battery charge failure (Site: E-DIGHI NORTH BLOCK GODDA)",
    "date": "19-06-2026",
    "downHours": 8.5,
    "severity": "Medium"
  },
  {
    "id": "BD-064",
    "machineId": "R-117",
    "partId": "P-112",
    "reason": "Burst hydraulic feed hose at secondary boom (Site: E-DIGHI NORTH BLOCK GODDA)",
    "date": "22-06-2026",
    "downHours": 48.5,
    "severity": "Critical"
  },
  {
    "id": "BD-065",
    "machineId": "R-104",
    "partId": "P-111",
    "reason": "Starter motor contacts pitted and failing to crank engine (Site: E-JINDAL)",
    "date": "01-06-2026",
    "downHours": 41.2,
    "severity": "High"
  },
  {
    "id": "BD-066",
    "machineId": "R-115",
    "partId": "P-105",
    "reason": "Sheared bolts on crawler track assembly under heavy terrain load (Site: E-FAGMIL KALOO POTASH)",
    "date": "17-06-2026",
    "downHours": 218,
    "severity": "Critical"
  },
  {
    "id": "BD-067",
    "machineId": "R-116",
    "partId": "P-114",
    "reason": "Restricted airflow and engine power loss from dust-clogged filters (Site: E-GSI JHAMARKOTRA)",
    "date": "23-06-2026",
    "downHours": 230.5,
    "severity": "Critical"
  },
  {
    "id": "BD-068",
    "machineId": "R-105",
    "partId": "P-111",
    "reason": "Restricted airflow and engine power loss from dust-clogged filters (Site: CEW)",
    "date": "03-06-2026",
    "downHours": 20,
    "severity": "Medium"
  }
];

const INITIAL_PROCUREMENT: ProcurementRecord[] = [
  {
    "poId": "PO-2026-001",
    "prId": "PR-2026-001",
    "partId": "P-114",
    "partName": "Hydraulic Pump Assembly",
    "quantity": 2,
    "unitPrice": 4500,
    "totalAmount": 9000,
    "requestedBy": "Hydraulics Team",
    "requestedDate": "2026-05-05",
    "approvedDate": "2026-05-08",
    "orderedDate": "2026-05-10",
    "receivedDate": "2026-05-18",
    "status": "Acquisition_Completed",
    "vendor": "Komatsu Heavy Parts Ltd"
  },
  {
    "poId": "PO-2026-002",
    "prId": "PR-2026-002",
    "partId": "P-103",
    "partName": "Engine Fuel Injector",
    "quantity": 10,
    "unitPrice": 850,
    "totalAmount": 8500,
    "requestedBy": "Engine Workshop",
    "requestedDate": "2026-05-12",
    "approvedDate": "2026-05-14",
    "orderedDate": "2026-05-16",
    "receivedDate": "",
    "status": "Shipped",
    "vendor": "CAT Parts International"
  },
  {
    "poId": "PO-2026-003",
    "prId": "PR-2026-003",
    "partId": "P-109",
    "partName": "Starter Motor 24V",
    "quantity": 5,
    "unitPrice": 650,
    "totalAmount": 3250,
    "requestedBy": "Electrical Dept",
    "requestedDate": "2026-05-20",
    "approvedDate": "2026-05-22",
    "orderedDate": "2026-05-25",
    "receivedDate": "",
    "status": "PO_Issued",
    "vendor": "Bosch Heavy Duty Store"
  }
];

const INITIAL_INDENTS: IndentRequest[] = [
  {
    "indentId": "IND-2026-001",
    "department": "Excavator Crew",
    "partId": "P-106",
    "partName": "Oil Filter",
    "quantity": 10,
    "date": "2026-05-31",
    "status": "Issued"
  },
  {
    "indentId": "IND-2026-002",
    "department": "DT Workshop",
    "partId": "P-105",
    "partName": "Air Filter Assembly",
    "quantity": 6,
    "date": "2026-06-01",
    "status": "Issued"
  }
];

export const getStoredData = (): DatabaseState => {
  const machines = localStorage.getItem("gm_machines");
  const inventory = localStorage.getItem("gm_inventory");
  const breakdowns = localStorage.getItem("gm_breakdowns");
  const procurement = localStorage.getItem("gm_procurement");
  const indents = localStorage.getItem("gm_indents");

  if (!machines || !inventory || !breakdowns || !procurement || !indents) {
    localStorage.setItem("gm_machines", JSON.stringify(INITIAL_MACHINES));
    localStorage.setItem("gm_inventory", JSON.stringify(INITIAL_INVENTORY));
    localStorage.setItem("gm_breakdowns", JSON.stringify(INITIAL_BREAKDOWNS));
    localStorage.setItem("gm_procurement", JSON.stringify(INITIAL_PROCUREMENT));
    localStorage.setItem("gm_indents", JSON.stringify(INITIAL_INDENTS));

    return {
      machines: INITIAL_MACHINES,
      inventory: INITIAL_INVENTORY,
      breakdowns: INITIAL_BREAKDOWNS,
      procurement: INITIAL_PROCUREMENT,
      indents: INITIAL_INDENTS
    };
  }

  return {
    machines: JSON.parse(machines),
    inventory: JSON.parse(inventory),
    breakdowns: JSON.parse(breakdowns),
    procurement: JSON.parse(procurement),
    indents: JSON.parse(indents)
  };
};

export const updateStoredData = (key: string, data: any): void => {
  localStorage.setItem(`gm_${key}`, JSON.stringify(data));
};
